### ISSUE TITLE
Possibility to batch query exchange rates

### ISSUE THREAD

**Issue by geekdevs** [florianv/exchanger#66]
I am using OpenExchangeRates service to regularly collect exchange rates for 50 currencies. 
What I see happening is that it is using `/api/latest.json` request which gets a list of all exchange rates, but the library essentially throws away all rates except for 1 pair at a time. So this leads to 50 requests being made (while it can only be done with 1) and rate limit is hit very quickly.

Is there a possibility to make batch request or e.g. cache response from the library?

**Comment by geekdevs** [comment]
I could solve it by adding caching with http client. Using kevinrob/guzzle-cache-middleware.

Might be useful to somebody:

`composer require kevinrob/guzzle-cache-middleware`

Symfony config:

```
    http.cache.array:
      class: Kevinrob\GuzzleCache\Storage\VolatileRuntimeStorage

    exchange.http.cache_strategy.public:
      class: Kevinrob\GuzzleCache\Strategy\PublicCacheStrategy
      arguments:
        - "@http.cache.array"

    exchange.http.cache.middleware:
      class: Kevinrob\GuzzleCache\CacheMiddleware
      arguments:
        - "@exchange.http.cache_strategy.public"

    exchange.http_client.buffered.handler_stack:
      class: GuzzleHttp\HandlerStack
      factory: [GuzzleHttp\HandlerStack, create]
      calls:
         - method: push
           arguments:
               - '@exchange.http.cache.middleware'
               - 'cache'

    exchange.guzzle.buffered:
      class: GuzzleHttp\Client
      arguments:
        - handler: "@exchange.http_client.buffered.handler_stack"

    exchange.http_client.buffered:
      class: Http\Adapter\Guzzle6\Client
      arguments: ["@exchange.guzzle.buffered"]

    ratio_provider.service.default:
      class: Exchanger\Service\OpenExchangeRates
      arguments:
        $httpClient: "@exchange.http_client.buffered"
        $options: {app_id: "%openexchange.app_id%"}
```
